<?php
/**
 * Language labels for database tables/fields belonging to extension "wec_connector"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"tt_content.list_type_pi1" => "WEC Connector",
		'wec_connector' => 'WEC Connector Community',

		"tx_wecconnector_entries" => "Connector Entry",
		"tx_wecconnector_entries.parent_uid" => "Parent connector board",
		"tx_wecconnector_entries.post_date" => "When this was posted",
		"tx_wecconnector_entries.category" => "Category this is linked to",
		"tx_wecconnector_entries.user_uid" => "userID of Poster",
		"tx_wecconnector_entries.name" => "Name (Who Posted)",
		"tx_wecconnector_entries.subject" => "Subject Of Post",
		"tx_wecconnector_entries.email" => "Email of Person Who Posted",
		"tx_wecconnector_entries.message" => "Message content",
		"tx_wecconnector_entries.phone" => "Phone number",
		"tx_wecconnector_entries.location" => "Location (city,state)",
		"tx_wecconnector_entries.address" => "Street/Mailing Address",
		"tx_wecconnector_entries.city" => "City",
		"tx_wecconnector_entries.state" => "State/province abbreviation",
		"tx_wecconnector_entries.zipcode" => "Zip/country code",
		"tx_wecconnector_entries.country" => "Country",
		"tx_wecconnector_entries.website_url" => "Website URL",
		"tx_wecconnector_entries.business_name" => "Business Name",
		"tx_wecconnector_entries.image" => "Photo / Picture",
		"tx_wecconnector_entries.contact_name" => "Contact Name",
		"tx_wecconnector_entries.email2" => "Contact Email",
		"tx_wecconnector_entries.responder_name" => "Name Of Who Responded",
		"tx_wecconnector_entries.responder_email" => "Email of Person Who Responded",
		"tx_wecconnector_entries.is_response" => "Is a response message?",
		
		"tx_wecconnector_group" => "Connector Group",
		"tx_wecconnector_group.parent_uid" => "Connector ID associated with",
		"tx_wecconnector_group.user_uid" => "Typo3 User ID",
		"tx_wecconnector_group.user_email" => "User Email",
		"tx_wecconnector_group.user_name" => "Name",

		"tx_wecconnector_cat" => "Connector Category",
		"tx_wecconnector_cat.title" => "Title",
		'tx_wecconnector_cat.image' => 'Category image',
		'tx_wecconnector_cat.sort_order' => 'Sort (display) order',

		'wec_connector.pi_flexform.sheet_main' => 'Main',
		'wec_connector.pi_flexform.name' => 'Name of Connector Board: ',
		'wec_connector.pi_flexform.entry_description' => 'Description of an Entry: ',
		'wec_connector.pi_flexform.entries_description' => 'Description of Entries (plural): ',
		'wec_connector.pi_flexform.entry_subject' => 'Subject For Entry Form: ',
		'wec_connector.pi_flexform.entry_button' => 'Submit Button Text: ',
		'wec_connector.pi_flexform.template_file' => 'Template file',
		'wec_connector.pi_flexform.category_selection' => 'View The Categories: ',
		'wec_connector.pi_flexform.category_selection_notCategorized' => 'No categories',

		'wec_connector.pi_flexform.sheet_display' 	=> 'Display',
		'wec_connector.pi_flexform.entry_look' 		=> 'How Entry Will Look?',
			'wec_connector.pi_flexform.entry_look_1' => 'Normal',
			'wec_connector.pi_flexform.entry_look_2' => 'Postboard',
			'wec_connector.pi_flexform.entry_look_3' => 'Business Listing',
			'wec_connector.pi_flexform.entry_look_4' => 'eCandle',
		'wec_connector.pi_flexform.message_length' 	=> 'Max \'message\' field length (in chars):',
		'wec_connector.pi_flexform.field_length' 	=> 'Max \'other\' field length (in chars):',
		'wec_connector.pi_flexform.days_to_keep' 	=> '# of days to keep:',
		'wec_connector.pi_flexform.display_per_page' => '# to display per page:',
		'wec_connector.pi_flexform.websiteURL_popup' => 'Make popup for website_url link',

		'wec_connector.pi_flexform.sheet_control' => 'Control',
		'wec_connector.pi_flexform.do_moderate' => 'Moderate all posts by administrator(s)?',
		'wec_connector.pi_flexform.do_moderate_response' => 'Moderate all responses by administrator(s)?',
		'wec_connector.pi_flexform.require_login_for_posting' => 'Require login for posting new request?',
		'wec_connector.pi_flexform.require_login_for_reply' => 'Require login for reply/respond?',
		'wec_connector.pi_flexform.usergroups_only_reply' => 'Choose usergroups that can only reply',
		'wec_connector.pi_flexform.who_can_edit' 	=> 'Who can edit/delete messages? ',
			'wec_connector.pi_flexform.editAdmin' 		=> 'Administrator',
			'wec_connector.pi_flexform.editPoster' 		=> 'User Who Posted/Admin',
			'wec_connector.pi_flexform.editAnyone' 		=> 'Anyone',
		'wec_connector.pi_flexform.can_subscribe' 	=> 'Can subscribe to this connector?',
		'wec_connector.pi_flexform.require_login_for_subscribing' => 'Require login for subscribing?',
		'wec_connector.pi_flexform.update_subscribe_btn' => 'Update Subscribe Button (so see unsubscribe)?',

		'wec_connector.pi_flexform.sheet_antispam' => 'Spam',
		'wec_connector.pi_flexform.spam_administrator' => 'Spam checker/receiver email/user(s); otherwise sends to Admin',
		'wec_connector.pi_flexform.html_tags_allowed'  => 'HTML Tags Allowed (0=none, 1=all, or list- <b><i>)',
		'wec_connector.pi_flexform.use_captcha' 		=> 'Use Image Captcha? (need sr_freecap or captcha)',
		'wec_connector.pi_flexform.use_text_captcha' 	=> 'Use Text captcha (field: "Are you a person?")',
		'wec_connector.pi_flexform.numlinks_allowed' 	=> 'Number of links allowed in post (0 = none)?',
		'wec_connector.pi_flexform.filter_wordlist' 	=> 'Filter word list (comma-delimited) use * for default: ',
		'wec_connector.pi_flexform.filter_word_handling' => 'What to do if filter words are found?',
			'wec_connector.pi_flexform.filterWordFilter' 	=> 'Filter',
			'wec_connector.pi_flexform.filterWordModerate' => 'Moderate To Admin',
			'wec_connector.pi_flexform.filterWordDiscard' 	=> 'Discard the Post',
		'wec_connector.pi_flexform.spam_check_responses' => 'Check Response Messages for Spam?',
			'wec_connector.pi_flexform.spamResponsesNone' 	=> 'Do not check',
			'wec_connector.pi_flexform.spamResponsesDiscard' => 'Discard Responses if spam',
			'wec_connector.pi_flexform.spamResponsesAdmin' 	=> 'Send to Admin if spam',
			'wec_connector.pi_flexform.spamResponsesModerate' 	=> 'Moderate if spam',
				
		'wec_connector.pi_flexform.sheet_fields' => 'Fields',
		'wec_connector.pi_flexform.display_fields' => 'Display Fields Shown On Form: ',
		'wec_connector.pi_flexform.required_fields' => 'Required Fields On Form: ',
		'wec_connector.pi_flexform.required_response_fields' => 'Required Fields On Response Form: ',
				
		'wec_connector.pi_flexform.sheet_group' 	=> 'Administrator',
		'wec_connector.pi_flexform.administrator_group' => 'Administrator list by UID or username - separate by comma:',
		'wec_connector.pi_flexform.administrator_usergroup' => 'Administrator usergroup(s)',
		'wec_connector.pi_flexform.contact_name'	=> 'Contact Name (for email):',
		'wec_connector.pi_flexform.contact_email' 	=> 'Contact Email (for email):',
		'wec_connector.pi_flexform.email_admin_posts' => 'Email admin all posts (not moderated)',
		'wec_connector.pi_flexform.notify_email' 	=> 'Email to notify for all posts & responses (optional)',

		'wec_connector.pi_flexform.sheet_text' => 'Text',
		'wec_connector.pi_flexform.post_instructions_text' => 'Instructions For Posting [HTML ok]: ',
		'wec_connector.pi_flexform.response_title' => 'Response Form Header Text [HTML ok]:',
		'wec_connector.pi_flexform.subscribe_header' => 'Subscribe/Unsubscribe Form Header Text [HTML ok]:',
		'wec_connector.pi_flexform.subscriber_emailHeader' => 'New Post - Email Header Text (optional):',
		'wec_connector.pi_flexform.subscriber_emailFooter' => 'New Post - Email Footer Text (optional):',
		
		'wec_connector.pi_flexform.sheet_preview' => 'Preview',
		'wec_connector.pi_flexform.is_preview' => 'Is A Preview?',
		'wec_connector.pi_flexform.preview_backPID' => 'Connector to link to',
		'wec_connector.pi_flexform.num_preview_items' 	=> 'Number of items to show',
		'wec_connector.pi_flexform.preview_length' 	=> 'Character length of a preview item',
	),
	"nl" => Array (
		"tx_wecconnector_entries" => "Connector ingang",
		"tx_wecconnector_entries.parent_uid" => "Ouderraad connector",
		"tx_wecconnector_entries.post_date" => "Toen dit gepost is",
		"tx_wecconnector_entries.category" => "Gelinkt aan categorie",
		"tx_wecconnector_entries.user_uid" => "userID van de poster",
		"tx_wecconnector_entries.name" => "Naam van degene die het gepost heeft",
		"tx_wecconnector_entries.subject" => "Onderwerp van de posting",
		"tx_wecconnector_entries.email" => "Email van degene die het gepost heeft",
		"tx_wecconnector_entries.message" => "Bericht inhoud",
		"tx_wecconnector_entries.phone" => "Telefoonnummer (incl. netnummer)",
		"tx_wecconnector_entries.location" => "Locatie (plaats, provincie)",
		"tx_wecconnector_entries.address" => "Straat/postadres",
		"tx_wecconnector_entries.city" => "Plaats",
		"tx_wecconnector_entries.state" => "Afkorting provincie",
		"tx_wecconnector_entries.zipcode" => "Postcode",
		"tx_wecconnector_entries.country" => "Land",
		"tx_wecconnector_entries.website_url" => "Website URL",
		"tx_wecconnector_entries.business_name" => "Naam bedrijf",
		"tx_wecconnector_entries.image" => "Foto/afbeelding",
		"tx_wecconnector_entries.contact_name" => "Contact naam",
		"tx_wecconnector_entries.email2" => "Contact email",
		"tx_wecconnector_group" => "Connector groep",
		"tx_wecconnector_group.parent_uid" => "Connector ID geassocieerd met",
		"tx_wecconnector_group.user_uid" => "TYPO3 userID in deze groep",
		"tx_wecconnector_group.user_email" => "Gebruiker email",
		"tx_wecconnector_group.user_name" => "Naam",
		"tx_wecconnector_cat" => "Connector categorie",
		"tx_wecconnector_cat.title" => "Titel",
		"tx_wecconnector_cat.image" => "Categorie afbeelding",
		"tx_wecconnector_cat.sort_order" => "Sorteer (toon) volgorde",
		"wec_connector" => "WEC connector community",
		"wec_connector.pi_flexform.sheet_main" => "Hoofd",
		"wec_connector.pi_flexform.name" => "Naam van de connector raad:",
		"wec_connector.pi_flexform.entry_description" => "Beschrijving van een item",
		"wec_connector.pi_flexform.entry_subject" => "Onderwerp voor item formulier:",
		"wec_connector.pi_flexform.entry_button" => "Verzend-knop tekst",
		"wec_connector.pi_flexform.template_file" => "Sjabloon bestand",
		"wec_connector.pi_flexform.category_selection" => "Toon de categorieën",
		"wec_connector.pi_flexform.category_selection_notCategorized" => "Geen categorieën",
		"wec_connector.pi_flexform.sheet_options" => "Opties",
		"wec_connector.pi_flexform.message_length" => "Maximale 'bericht' veldlengte (in tekens):",
		"wec_connector.pi_flexform.field_length" => "Maximale 'ander' veldlengte (in tekens):",
		"wec_connector.pi_flexform.days_to_keep" => "# dagen bewaren:",
		"wec_connector.pi_flexform.display_per_page" => "# te tonen per pagina:",
		"wec_connector.pi_flexform.who_can_edit" => "Wie kan berichten bewerken/verwijderen?",
		"wec_connector.pi_flexform.editAdmin" => "Administrator",
		"wec_connector.pi_flexform.editPoster" => "Poster/Admin",
		"wec_connector.pi_flexform.editAnyone" => "Iedereen",
		"wec_connector.pi_flexform.can_subscribe" => "Kan inschrijven op deze connector:",
		"wec_connector.pi_flexform.bad_wordlist" => "Foute woorden filter lijst (komma gescheiden); gebruik * voor de standaard:",
		"wec_connector.pi_flexform.bad_word_handling" => "Wat te doen bij foute woorden?",
		"wec_connector.pi_flexform.badwordFilter" => "Filter",
		"wec_connector.pi_flexform.badwordModerate" => "Stuur naar administrator",
		"wec_connector.pi_flexform.badwordDiscard" => "Negeer de posting",
		"wec_connector.pi_flexform.login_for_posting" => "Login nodig om te posten:",
		"wec_connector.pi_flexform.login_for_subscribing" => "Login nodig voor inschrijving",
		"wec_connector.pi_flexform.websiteURL_popup" => "Maak een popup voor de website link",
		"wec_connector.pi_flexform.sheet_fields" => "Verplichte velden",
		"wec_connector.pi_flexform.required_fields" => "Verplichte velden:",
		"wec_connector.pi_flexform.sheet_group" => "Administrator/Contact",
		"wec_connector.pi_flexform.contact_name" => "Naam van contact (voor mail):",
		"wec_connector.pi_flexform.contact_email" => "Emailadres van contact (voor mail):",
		"wec_connector.pi_flexform.administrator_group" => "Administrator(s) -- UID of gebruikersnaam (komma gescheiden):",
		"wec_connector.pi_flexform.do_moderate" => "Modereer alle postingen door de administrator (maak de admin aan)?",
		"wec_connector.pi_flexform.notify_email" => "Emailadres voor het melden van alle postingen en antwoorden (optioneel)",
		"wec_connector.pi_flexform.sheet_text" => "Tekst",
		"wec_connector.pi_flexform.post_instructions_text" => "Instructies voor postingen [HTML toegestaan]",
		"wec_connector.pi_flexform.response_title" => "Koptekst antwoordformulier [HTML toegestaan]",
		"wec_connector.pi_flexform.subscribe_header" => "Koptekst aanmeld/afmeld formulier [HTML toegestaan]",
		"wec_connector.pi_flexform.subscriber_emailHeader" => "Koptekst nieuwe posting email (optioneel)",
		"wec_connector.pi_flexform.subscriber_emailFooter" => "Afsluittekst nieuwe posting email (optioneel)",
		"tt_content.list_type_pi1" => "WEC connector",
	),


);
?>