<?php

$LOCAL_LANG = Array (
	'default' => Array (
        'pi1_title' => 'WEC Connector',
        'pi1_plus_wiz_description' => 'Add a connector',

		'back' => 'Back',
		'submit_button_label' => 'Click here to submit value',
		'next_page' 		=> 'next',
		'prev_page' 		=> 'prev',
		'page_name' 		=> 'Page #',
		'category_divider' 	=> '  ',
		'pagenum_divider' 	=> '...',
		'subscribe_btn' 	=> 'Subscribe',
		'unsubscribe_btn'	=> 'Unsubscribe',
		'moderate_btn' 		=> 'Moderate',
		'respond_btn' 		=> 'Respond',
		'edit_btn' 			=> 'Edit',
		'delete_btn' 		=> 'Delete',
		'delete_confirm' 	=> 'Are you sure you want to delete?',
		'hide_btn'			=> 'Hide',
		'hide_confirm'		=> 'Are you sure you want to hide this?',
		'cancel_btn' 		=> 'Cancel',
		'viewall_btn' 		=> 'View All',
		'show_required_text' => '<span class="required">*</span> = required field',
		'post_bad_words' 	=> 'Your post had inappropriate words in it and was discarded.',
		'post_duplicate'  	=> 'Your post has already been added. You do not need to send it again.',
		'choose_category' 	=> 'Choose Category: ',

		'message_added'		=> 'Your message was added.',
		'message_moderated' => 'This is moderated -- you will not see your message until it is approved.',
		'message_updated'	=> 'Your message has been updated.',
		'respond_success' 	=> 'Your reply was sent successfully.',
		'respond_header'  	=> 'This email is sent from your request on: ',
		'respond_error1'  	=> 'Your reply could not be sent due to a bad email address for this message.',
		'respond_error2'  	=> 'Your reply could not be sent.',
		'delete_success'  	=> 'You deleted the message.',
		'delete_failure'    => 'There was a problem deleting the message.',
		'delete_cannot'		=> 'You do not have permission to delete this message.',
		'hide_success'  	=> 'You hid the message.',
		'hide_failure'    	=> 'There was a problem hiding the message.',
		'hide_cannot'		=> 'You do not have permission to hide this message.',

		'subscribe_success' => 'You are now subscribed to this group.',
		'subscribe_error1' 	=> 'Please provide your email address.',
		'subscribe_error2' 	=> 'Please provide a valid email in the form name@web.com',
		'subscribe_error3' 	=> 'You are already subscribed to this group.',
		'unsubscribe_error' => 'You are not subscribed -- we could not find your email. Please check the spelling of the e-mail address and try again:',

		'new_emailSubject' 	=> 'New ',
		'entry_description' => 'Request',
		'email_subject' 	=> 'Subject: ',
		'email_message' 	=> 'Message: ',
		'email_postedby' 	=> 'Posted By: ',
		'email_category' 	=> 'Category: ',
		'email_locatedin' 	=> 'Located In: ',
		'email_unsubscribe' => "\n-------------------------------------------\nTo be unsubscribed from this list and not receive these emails anymore, please click or go to this URL: ",
		'email_notify' 		=> 'NOTIFY: ',
		'email_gotolink' 	=> 'Go to link: ',
		'email_moderateMsg' => 'Moderate Message For ',

		'form_name' 	=> 'Your Name',
		'form_subject' 	=> 'Subject',
		'form_email' 	=> 'Your Email',
		'form_message' 	=> 'Message',
		'form_phone' 	=> 'Phone number',
		'form_location' => 'Location',
		'form_address' 	=> 'Street/Mailing Address',
		'form_city' 	=> 'City',
		'form_state' 	=> 'State',
		'form_zipcode' 	=> 'Zip code',
		'form_country' 	=> 'Country',
		'form_website_url' => 'Website URL',
		'form_business_name' => 'Business Name',
		'form_contact_name' => 'Contact Name',
		'form_category' => 'Select Category',
		'form_image' 	=> 'Choose Image',
		'form_submit' 	=> 'Submit',
		'form_legend'	=> 'Enter Your Request',

		'form_name_instructions' => 'Please fill out your name here. Leave blank to remain anonymous.',
		'form_subject_instructions' => 'Please fill out the subject of your post here.',
		'form_email_instructions' => 'Your email will not appear on the website, but please provide it if you want people to privately respond to you.',
		'form_message_instructions' => 'Please make a full description. Note that you will be contacted by email if your email is given.',
		'form_location_instructions' => 'Please enter your city &amp; state.',

		'form_error'  		 => 'You have error(s) in the following:',
		'form_invalid_field' => 'invalid entry',
		'form_required_blank' => 'entry needs to be filled in',
		'form_invalid_field_length' => 'entry too long',

		'form_toggleOn' 	=>	'Add An Entry',
		'form_toggleOff' 	=>	'Hide Entry',

		'responseform_name' 	=> 'Your Name',
		'responseform_subject' 	=> 'Subject',
		'responseform_email'   	=> 'Your Email',
		'responseform_message' 	=> 'Your Reply',
		'responseform_submit'  	=> 'Reply',
		'responseform_cancel'  	=> 'Cancel',

		'subscribeform_name' 	=> 'Your Name',
		'subscribeform_email'   => 'Your Email',
		'subscribeform_submit_sub'  => 'Subscribe',
		'subscribeform_submit_unsub'  => 'Unsubscribe',
		'subscribeform_cancel'  => 'Cancel',

		'modify_delete_header' => '<h3>MODIFY</h3>',
		'modify_request' 		=> 'Modify Request',

		'edit_denied'		=> 'You do not have permission to edit this message.',
		'edit_failure'		=> 'You cannot edit this message.',
		'email_moderateMsgHeader'	=> "Need to Moderate New Message:\n\n",
		'email_from'		=> 'From: ',

		'no_entries'		=> 'There are no entries yet.',
		'no_javascript_for_post' => 'You must have Javascript enabled to post a message.',

        'display_header'		=> 'Current',
        'display_header_plurals' => 's',
        'display_total_category' => 'in category',
        'display_total'			=> 'total',

		'captcha_bad'		=> 'Please try entering the text for the image check again.',
		'textcaptcha_field' => 'Are you a person?',
		'textcaptcha_bad'	=> 'You need to fill out the "Are you a person?" field',
		'too_many_links'	=> 'Too many links found -- only allowed ',
		'email_none'		=> '<noemail@here.com>',

		'login_to_post'		=> 'You must login to post here.',
		'login_to_reply'	=> 'If you want to respond to one of these, you must login.',

		'no_links_allowed'	=> 'You cannot post any links here.',

		'back_button'		=> 'Go back',

		'anonymous' 		=> 'Anonymous',
		'no_subject' 		=> '(no subject)',

		'preview_none' 		=> 'There is nothing posted yet.',
		'postedby_text' 	=> 'Posted By:',
		'on_text'			=> 'on',
		'preview_goto_link' => 'Check this out',

		'errorIncludeStatic'=> 'You must include static "WEC Connector template" in the page template to see any output',

		'admin_btn'			=> 'Admin',
		'admin_menu_header'	=> 'Admin Menu',
		'admin_show_subscribers_header'	=> 'List Of Subscribers To This Connector',
		'admin_subscribers_none' => 'no subscribers yet',
		'admin_exit'		=> 'Exit',
		'admin_show_subscribers' => 'Show Subscribers',
		
		'email_received_text'=> 'has been received at:',
		'respond_error_spam' => '',
		'email_notify_spam'  => 'NOTIFY SPAM RESPONSE:',
		'spam_notify1'		=> 'Spam determined in response sent from ',
		'spam_notify2'		=> ' in response to message posted by',
		'notify_response_header'=> 'NOTIFY RESPONSE:',
		'notify_response_msg1'	=> 'Email sent from ',
		'notify_response_msg2'	=> ' in response to ',
		'ip_address_field'	=> 'IP: ',
		'respond_to_message' => 'Response to message:',
		'respond_success2'	=> 'Your reply should be sent soon.',
		'response_header'	=> 'Respond to Original Message:',
		
		'form_captcha_label' => 'Enter text from image',
		'login_to_moderate' => 'You need to be logged in to moderate. ',
		'goto_login'		=> 'Goto Login',
		
	),
	'dk' => Array (
		'back' => 'Tilbage',
	),
	'de' => Array (
        'pi1_title' => 'WEC Connector',
        'pi1_plus_wiz_description' => 'Connector hinzufügen',

        'back' => 'Zurück',
        'submit_button_label' => 'Abschicken',
        'next_page'             => 'Weiter',
        'prev_page'             => 'Zurück',
        'page_name'             => 'Seite #',
        'category_divider'      => '  ',
        'pagenum_divider'       => '...',
        'subscribe_btn' => 'Beobachten',
        'moderate_btn'          => 'Moderieren',
        'respond_btn'           => 'Antworten',
        'edit_btn'              => 'Bearbeiten',
        'delete_btn'            => 'Löschen',
        'delete_confirm' => 'Sind Sie sicher, dass Sie diesen Eintrag löschen wollen?',
        'cancel_btn'            => 'Abbrechen',
        'viewall_btn'           => 'Alles anzeigen',
        'show_required_text' => '* = benötigte Felder',
		'post_bad_words'        => 'Ihr Eintrag enthält unerwünschte Wörter. Er wurde abgelehnt.',
		'post_duplicate'        => 'Ihr Eintrag wurde schon hinzugefügt. Sie brauchen ihn nicht noch einmal abzuschicken.',
		'choose_category'       => 'Wählen Sie eine Kategorie: ',

        'message_added'         => 'Ihr Eintrag wurde hinzugefügt.',
		'message_moderated' 	=> 'Dieser Bereich ist moderiert -- Sie werden Ihren Eintrag sehen, sobald er akzeptiert wurde.',
		'message_updated'       => 'Ihr Eintrag wurde aktualisiert.',
		'respond_success'       => 'Ihre Antwort ist erfolgreich verschickt worden.',
		'respond_header'        => 'Diese Email wurde auf eine Anfrage verschickt von: ',
		'respond_error1'        => 'Ihre Antwort konnte nicht verschickt werden. Sie haben eine fehlerhafte Email-Adresse angegeben.',
		'respond_error2'        => 'Ihre Antwort konnte nicht verschickt werden.',
        'delete_success'        => 'Sie haben den Eintrag gelöscht.',
		'delete_failure'    	=> 'Es gab ein Problem beim Löschen des Eintrags.',
		'delete_cannot'         => 'Sie haben keine Berrechtigung, um diesen Eintrag zu löschen.',
        'subscribe_success' 	=> 'Sie haben diese Gruppe jetzt abonniert.',
		'subscribe_error1'      => 'Bitte geben Sie Ihre Email-Adresse an.',
		'subscribe_error2'      => 'Bitte geben Sie ihre Email-Adresse in der Form name@web.de an (z.B. mothergoose@aol.com, jacksprat@yahoo.com)',
        'subscribe_error3'      => 'Sie haben diese Gruppe schon abonniert.',
		'unsubscribe_error' 	=> 'Sie können diese Gruppe nicht abonnieren -- Ihre Email-Adresse konnte nicht akzeptiert werden. Bitte überprüfen sie ihre Email-Adresse und versuchen Sie es erneut.',

        'new_emailSubject'        => 'Neu ',
        'entry_description' => 'Anfrage',
        'email_subject'   => 'Betreff: ',
        'email_message'         => 'Eintrag: ',
        'email_postedby'        => 'Erstellt von: ',
        'email_category'        => 'Kategorie: ',
        'email_locatedin'       => 'Eintrag in: ',
		'email_unsubscribe' 	=> "\n-------------------------------------------\nWenn sie das Abonement beenden und keine Emails mehr bekommen wollen, klicken Sie bitte auf diesen Link: ",
        'email_notify'          => 'Wichtig: ',
        'email_gotolink' 		=> 'Link besuchen: ',
        'email_moderateMsg' 	=> 'Moderieren sie den Eintrag für ',

        'form_name'       	=> 'Ihr Name',
        'form_subject'    	=> 'Betreff',
        'form_email'       	=> 'Ihre Email-Adresse',
        'form_message'     	=> 'Eintrag',
        'form_phone'      	=> 'Telefon',
        'form_location' 	=> 'Adresse',
        'form_address'   	=> 'Strass',
        'form_city'         => 'Stadt',
        'form_state'       	=> 'Bundesland',
        'form_zipcode'   	=> 'Postleitzahl',
        'form_country'    	=> 'Land',
        'form_website_url' 	=> 'Website URL',
        'form_business_name' => 'Firmenname',
        'form_contact_name' => 'Kontaktperson',
        'form_category' 	=> 'Kategorie auswählen',
        'form_image'      	=> 'Bild auswählen',
        'form_submit'     	=> 'Abschicken',

		'form_name_instructions' => 'Bitte geben Sie hier Ihren Namen ein',
		'form_subject_instructions' => 'Bitte geben Sie den Betreff hier an',
		'form_email_instructions' => 'Achtung: Ihre Email-Adresse wird auf der Seite nicht angezeigt.',
		'form_message_instructions' => 'Bitte geben Sie eine Beschreibung an. Sie werden per Email kontaktiert.',
		'form_location_instructions' => 'Bitte geben Sie Ihre Stadt an',

		'form_error'         => 'Folgende Fehler sind aufgetreten:',
		'form_invalid_field' => 'Ungültiger Wert',
		'form_required_blank' => 'Dieses Feld muss zwingend ausgefüllt werden',
		'form_invalid_field_length' => 'Der Inhalt für dieses Feld ist zu lang',

        'form_toggleOn' =>        'Eintrag hinzufügen',
        'form_toggleOff' =>        'Eintrag verstecken',

        'responseform_name'      => 'Ihr Name',
        'responseform_subject'   => 'Betreff',
        'responseform_email'     => 'Email-Adresse',
        'responseform_message'   => 'Ihre Antwort',
        'responseform_submit'    => 'Antworten',
        'responseform_cancel'    => 'Abbrechen',

        'subscribeform_name'    => 'Ihr Name',
        'subscribeform_email'   => 'Ihre Email-Adresse',
        'subscribeform_submit_sub'  => 'Abonnieren',
        'subscribeform_submit_unsub'  => 'Abonement beenden',
        'subscribeform_cancel'  => 'Abbrechen',

        'modify_delete_header' => '<b>Bearbeiten / Löschen</b>',
		'modify_request' 		=> 'Eintrag ändern',
		'edit_denied'           => 'Sie haben keine Berechtigung diesen Eintrag zu ändern.',
		'edit_failure'          => 'Sie können diesen Eintrag nicht ändern.',
        'email_moderateMsgHeader' => "Ein neuer Eintrag muss moderiert werden:\n\n",
        'email_from'            => 'von: ',

        'no_entries'            => 'Es gibt zur Zeit keine Einträge.',
		'anonymous' 			=> 'Anonym',
		'no_subject' 			=> '(kein Betreff)',

        'postedby_text'        => 'Erstellt von: ',
    ),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
		'pi1_title' => 'WEC Connector',
		'pi1_plus_wiz_description' => 'Voeg een connector toe',
		'back' => 'terug',
		'submit_button_label' => 'Klik hier om de waarde te verzenden',
		'next_page' => 'volgende',
		'prev_page' => 'vorige',
		'page_name' => 'Pagina #',
		'category_divider' => '  ',
		'pagenum_divider' => '...',
		'subscribe_btn' => 'Inschrijven',
		'moderate_btn' => 'Beheren',
		'respond_btn' => 'Antwoord',
		'edit_btn' => 'Bewerk',
		'delete_btn' => 'Verwijder',
		'delete_confirm' => 'Verwijderen - zeker weten?',
		'cancel_btn' => 'Opheffen',
		'viewall_btn' => 'Toon alles',
		'show_required_text' => '* = verplicht veld',
		'post_bad_words' => 'Je posting bevat onacceptabele woorden en is verwijderd.',
		'post_duplicate' => 'Je posting is al toegevoegd. Je hoeft het niet opnieuw insturen.',
		'choose_category' => 'Kies een categorie:',
		'message_added' => 'Je bericht is toegevoegd.',
		'message_moderated' => 'Dit gebied wordt gemoddereerd -- het wordt zichtbaar nadat het goedgekeurd is.',
		'message_updated' => 'Je bericht is bijgewerkt.',
		'respond_success' => 'Je antwoord is goed verzonden.',
		'respond_header' => 'Deze mail is verzonden door jouw aanvraag op:',
		'respond_error1' => 'Je antwoord kan niet worden verzonden door een ongeldig emailadres.',
		'respond_error2' => 'Je antwoord kan niet verzonden worden.',
		'delete_success' => 'Je wiste het bericht',
		'delete_failure' => 'Er trad een probleem op bij het verwijderen van het bericht.',
		'delete_cannot' => 'Het hebt onvoldoende rechten om dit bericht te verwijderen',
		'subscribe_success' => 'Je bent nu ingeschreven bij deze groep.',
		'subscribe_error1' => 'Vul s.v.p. je emailadres is.',
		'subscribe_error2' => 'Geef s.v.p. een geldig emailadres in de vorm naam@web.com (b.v. mothergoose@aol.com, jacksprat@yahoo.com))',
		'subscribe_error3' => 'Je bent al ingeschreven bij deze groep',
		'unsubscribe_error' => 'We kunnen je emailadres niet vinden -- je bent hier schijnbaar nog niet ingeschreven.',
		'new_emailSubject' => 'Nieuw',
		'entry_description' => 'Aanvraag',
		'email_subject' => 'Onderwerp:',
		'email_message' => 'Bericht:',
		'email_postedby' => 'Gepost door:',
		'email_category' => 'Categorie:',
		'email_locatedin' => 'Woonachtig in:',
		'email_unsubscribe' => "\n-------------------------------------------\nOm uit te schrijven van deze lijst en deze emails niet meer te ontvangen, klik of ga s.v.p. naar deze URL:",
		'email_notify' => 'BERICHT:',
		'email_gotolink' => 'Ga naar de link:',
		'email_moderateMsg' => 'Modereer bericht voor:',
		'form_name' => 'Je naam',
		'form_subject' => 'Onderwerp',
		'form_email' => 'Je emailadres:',
		'form_message' => 'Bericht',
		'form_phone' => 'telefoonnummer',
		'form_location' => 'Locatie',
		'form_address' => 'Straat/postadres',
		'form_city' => 'Plaats',
		'form_state' => 'Porvincie',
		'form_zipcode' => 'Postcode',
		'form_country' => 'Land',
		'form_website_url' => 'Website URL',
		'form_business_name' => 'Bedrijfsnaam',
		'form_contact_name' => 'Naam contactpersoon',
		'form_category' => 'Kies categorie',
		'form_image' => 'Kies afbeelding',
		'form_submit' => 'verstuur',
		'form_name_instructions' => 'Vul s.v.p. je naam hier in',
		'form_subject_instructions' => 'Vul s.v.p. het onderwerp hier in',
		'form_email_instructions' => 'Besef dat je emailadres NIET getoond wordt op de website.',
		'form_message_instructions' => 'beschrijf s.v.p. volledig. Besef dat per email contact opgenomen wordt.',
		'form_location_instructions' => 'Vul s.v.p. je woonplaats en provincie in',
		'form_error' => 'Je hebt fouten gemaakt in:',
		'form_invalid_field' => 'ongeldige invoer',
		'form_required_blank' => 'veld dient te zijn ingevuld',
		'form_invalid_field_length' => 'invoer te lang',
		'form_toggleOn' => 'Voeg een veld toe',
		'form_toggleOff' => 'Verberg het veld',
		'responseform_name' => 'Je naam',
		'responseform_subject' => 'Onderwerp',
		'responseform_email' => 'Je emailadres',
		'responseform_message' => 'Je antwoord',
		'responseform_submit' => 'Antwoord',
		'responseform_cancel' => 'Herroep',
		'subscribeform_name' => 'Je naam',
		'subscribeform_email' => 'Je emailadres',
		'subscribeform_submit_sub' => 'Inschrijven',
		'subscribeform_submit_unsub' => 'Uitschrijven',
		'subscribeform_cancel' => 'Herroep',
		'modify_delete_header' => '<b>WIJZIG / VERWIJDER</b>',

		'postedgy_text' => 'Gepost door:',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
        'pi1_title' => 'WEC Connector',
        'pi1_plus_wiz_description' => 'Lisää connector',

		'back' => 'Takaisin',
		'submit_button_label' => 'Tallenna tiedot',
		'next_page' 		=> 'seuraava',
		'prev_page' 		=> 'edellinen',
		'page_name' 		=> 'Sivu #',
		'category_divider' 	=> '  ',
		'pagenum_divider' 	=> '...',
		'subscribe_btn' 	=> 'Liity',
		'moderate_btn' 		=> 'Moderoi',
		'respond_btn' 		=> 'Vastaa',
		'edit_btn' 			=> 'Muokkaa',
		'delete_btn' 		=> 'Poista',
		'delete_confirm' 	=> 'Oletko varma, että haluat poistaa?',
		'cancel_btn' 		=> 'Peruuta',
		'viewall_btn' 		=> 'Kaikki',
		'show_required_text' => '* = vaadittu kenttä',
		'post_bad_words' 	=> 'Viestissäsi oli sopimattomia sanoja ja se on poistettu.',
		'post_duplicate'  	=> 'Viestisi on jo lisätty.',
		'choose_category' 	=> 'Valitse kategoria: ',
		'form_toggleOn' 	=>	'Lisää viesti',
		'form_toggleOff' 	=>	'Piilota viesti',

		'message_added'		=> 'Viestisi on lisätty.',
		'message_moderated' => 'Tätä aluetta on moderoitu -- et näe viestiäsi ennen kuin se on hyväksytty.',
		'message_updated'	=> 'Viestisi on päivitetty.',
		'respond_success' 	=> 'Vastauksesi on lähetetty.',
		'respond_header'  	=> 'This email is sent from your request on: ',
		'respond_error1'  	=> 'Vastaustasi ei voitu lähettää epävalidin sähköpostiosoitteen vuoksi.',
		'respond_error2'  	=> 'Viestiäsi ei voitu lähettää.',
		'delete_success'  	=> 'Viesti poistettu.',
		'delete_failure'    => 'Viestiä ei voitu poistaa.',
		'delete_cannot'		=> 'Sinulla ei ole oikeuksia poistaa tätä viestiä.',
		'subscribe_success' => 'Olet liittynyt tälle listalle.',
		'subscribe_error1' 	=> 'Ole hyvä ja anna sähköpostiosoitteesi.',
		'subscribe_error2' 	=> 'Ole hyvä ja anna sähköpostiosoitteesi oikeassa muodossa, esim. nimi@web.fi',
		'subscribe_error3' 	=> 'Olet jo liittynyt tälle listalle.',
		'unsubscribe_error' => 'Et ole liittynyt listalle - sähköpostiosoitettasi ei löytynyt. Ole hyvä ja yritä uudelleen.',
		'no_entries'		=> 'Ei viestejä vielä.',
		'new_emailSubject' 	=> 'Uusi ',
		'entry_description' => 'Kuvaus',
		'email_subject' 	=> 'Otsikko: ',
		'email_message' 	=> 'Viesti: ',
		'email_postedby' 	=> 'Lähettäjä: ',
		'email_category' 	=> 'Kategoria: ',
		'email_locatedin' 	=> 'Paikkakunta: ',
		'email_unsubscribe' => "\n-------------------------------------------\nTo poistuaksesi postituslistalta klikkaa: ",
		'email_notify' 		=> 'HUOMAUTUS: ',
		'email_gotolink' 	=> 'Linkki: ',
		'email_moderateMsg' => 'Moderoi viestiä ',

		'form_name' 	=> 'Nimesi',
		'form_subject' 	=> 'Aihe',
		'form_email' 	=> 'Sähköpostisi',
		'form_message' 	=> 'Viesti',
		'form_phone' 	=> 'Puhelinnumero',
		'form_location' => 'Paikkakunta',
		'form_address' 	=> 'Katu/postiosoite',
		'form_city' 	=> 'Kaupunki',
		'form_state' 	=> 'State',
		'form_zipcode' 	=> 'postinro',
		'form_country' 	=> 'Maa',
		'form_website_url' => 'Www-osoite',
		'form_business_name' => 'Yrityksen nimi',
		'form_contact_name' => 'Yhteyshenkilö',
		'form_category' => 'Valitse kategoria',
		'form_image' 	=> 'Valitse kuva',
		'form_submit' 	=> 'Lähetä',

		'form_name_instructions' => 'Ole hyvä ja anna nimesi',
		'form_subject_instructions' => 'Ole hyvä ja anna otsikko',
		'form_email_instructions' => 'Huomaathan, että sähköpostiosoitteesi EI tule näkymään ilmoitustaululla.',
		'form_message_instructions' => 'Anna kuvaus. Sinuun otetaan yhteyttä sähköpostitse.',
		'form_location_instructions' => 'Anna kaupunki',

		'form_error'  		 => 'Virheitä seuraavissa:',
		'form_invalid_field' => 'epävalidi syöte',
		'form_required_blank' => 'pakollinen kenttä',
		'form_invalid_field_length' => 'liian pitkä',

		'form_toggleOn' 	=>	'Lisää ilmoitus',
		'form_toggleOff' 	=>	'Piilota lomake',

		'responseform_name' 	=> 'Nimesi',
		'responseform_subject' 	=> 'Otsikko',
		'responseform_email'   	=> 'Sähköpostisi',
		'responseform_message' 	=> 'Vastauksesi',
		'responseform_submit'  	=> 'Vastaa',
		'responseform_cancel'  	=> 'Peruuta',

		'subscribeform_name' 	=> 'Nimesi',
		'subscribeform_email'   => 'Sähköpostisi',
		'subscribeform_submit_sub'  => 'Liity postituslistalle',
		'subscribeform_submit_unsub'  => 'Poistu postituslistalta',
		'subscribeform_cancel'  => 'Peruuta',

		'modify_delete_header' => '<b>MUOKKAA / POISTA</b>',

		'edit_denied'		=> 'Sinulla ei ole oikeuksia muokata tätä viestiä.',
		'edit_failure'		=> 'Et voi muokata tätä viestiä.',
		'email_moderateMsgHeader'	=> "Moderoitava uusi viesti:\n\n",
		'email_from'		=> 'Lähettäjä: ',

		'no_entries'		=> 'Ei vielä viestejä.',

        'display_header' => 'Viimeiset',
        'display_header_plurals' => 't',
        'display_total_category' => 'kategoriassa',
        'display_total' => 'yhteensä',


		'postedby_text' 	=> 'Lähettäjä: ',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
		"back" => '&#36820;&#22238;',
		"cancel_btn" => '&#21462;&#28040;',
		"captcha_bad" => '&#35831;&#20877;&#27425;&#36755;&#20837;&#22270;&#29255;&#37324;&#30340;&#25991;&#23383;',
		"choose_category" => '&#36873;&#25321;&#31867;',
		"delete_btn" => '&#21024;&#38500;',
		"delete_cannot" => '&#26080;&#26435;&#21024;&#38500;&#31995;&#20449;&#24687;',
		"delete_confirm" => '&#30830;&#23450;&#21024;&#38500;&#65311;',
		"delete_failure" => '&#26080;&#27861;&#21024;&#38500;&#12290;',
		"delete_success" => '&#24050;&#21024;&#38500;&#12290;',
		"display_header" => '&#30446;&#21069;',
		"display_header_plurals" => '&#65286;nbsp;',
		"display_total" => '&#25152;&#26377;',
		"display_total_category" => '&#22312;&#27492;&#31867;',
		"edit_btn" => '&#20462;&#25913;',
		"edit_denied" => '&#26080;&#26435;&#20462;&#25913;&#27492;&#20449;&#24687;&#12290;',
		"edit_failure" => '&#26080;&#27861;&#20462;&#25913;&#27492;&#20449;&#24687;',
		"email_category" => '&#31867;&#65306;',
		"email_from" => '&#33258;&#65306;',
		"email_gotolink" => '&#38142;&#25509;&#21040;&#65306;',
		"email_locatedin" => '&#20301;&#32622;&#65306;',
		"email_message" => '&#20449;&#24687;&#65306;',
		"email_moderateMsg" => '&#23457;&#25209;&#20449;&#24687;',
		"email_moderateMsgHeader" => '&#38656;&#35201;&#23457;&#25209;&#20449;&#24687;&#65306;&lt;br /&gt;&lt;br /&gt; ',
		"email_none" => '&lt;noreply@here.com&gt;',
		"email_notify" => '&#27880;&#24847;&#65306;',
		"email_postedby" => '&#21457;&#24067;&#32773;&#65306;',
		"email_subject" => '&#20027;&#39064;&#65306;',
		"email_unsubscribe" => '-------------------------------------------&lt;br /&gt;&#21462;&#28040;&#35746;&#38405;&#12289;&#25298;&#32477;&#25910;&#21040;&#30005;&#37038;&#65292;&#35831;&#28857;&#20987;&#65306;',
		"entry_description" => '&#35201;&#27714;',
		"form_address" => '&#22320;&#22336;&#65306;',
		"form_business_name" => '&#20844;&#21496;&#21517;&#31216;&#65306;',
		"form_category" => '&#35831;&#36873;&#25321;&#31867;',
		"form_city" => '&#22478;&#24066;',
		"form_contact_name" => '&#22995;&#21517;',
		"form_country" => '&#22269;&#23478;',
		"form_email" => '&#30005;&#37038;&#22320;&#22336;',
		"form_email_instructions" => '&#24744;&#30340;&#30005;&#37038;&#22320;&#22336;&#23558;&#19981;&#20250;&#26174;&#31034;&#22312;&#32593;&#31449;&#19978;&#12290;&#20294;&#26159;&#20026;&#20351;&#21035;&#20154;&#21487;&#20197;&#32473;&#20320;&#21457;&#31169;&#20154;&#20449;&#24687;&#65292;&#35831;&#25552;&#20379;&#24744;&#30340;&#30005;&#37038;&#22320;&#22336;&#12290;',
		"form_error" => '&#38169;&#35823;&#65306;',
		"form_image" => '&#36873;&#25321;&#22270;&#29255;',
		"form_invalid_field" => '&#26080;&#25928;&#35760;&#24405;',
		"form_invalid_field_length" => '&#35760;&#24405;&#36807;&#38271;',
		"form_location" => '&#22320;&#22336;',
		"form_location_instructions" => '&#22478;&#24066;',
		"form_message" => '&#20449;&#24687;',
		"form_message_instructions" => '&#25551;&#36848;&#12290;&#27880;&#24847;&#65306;&#20551;&#22914;&#25552;&#20379;&#20102;&#30005;&#37038;&#30340;&#35805;&#23558;&#20250;&#19982;&#24744;&#32852;&#31995;&#12290;',
		"form_name" => '&#22995;&#21517;',
		"form_name_instructions" => '&#22635;&#20837;&#22995;&#21517;&#25110;&#26174;&#31034;&#20026;&#26080;&#21517;&#27663;&#12290;',
		"form_phone" => '&#30005;&#35805;',
		"form_required_blank" => '&#24517;&#22635;&#27492;&#39033;',
		"form_state" => '&#30465;',
		"form_subject" => '&#20027;&#39064;',
		"form_subject_instructions" => '&#35831;&#22635;&#20889;&#20027;&#39064;&#12290;',
		"form_submit" => '&#25552;&#20132;',
		"form_toggleOff" => '&#38544;&#34255;',
		"form_toggleOn" => '&#28155;&#21152;',
		"form_website_url" => '&#32593;&#31449;&#32593;&#22336;',
		"form_zipcode" => '&#37038;&#32534;',
		"login_to_post" => '&#35831;&#20808;&#30331;&#24405;',
		"login_to_reply" => '&#35831;&#20808;&#30331;&#24405;',
		"message_added" => '&#24050;&#28155;&#21152;&#12290;',
		"message_moderated" => '&#20449;&#24687;&#23457;&#25209;&#20013;&#12290;',
		"message_updated" => '&#20449;&#24687;&#24050;&#26356;&#26032;&#12290;',
		"moderate_btn" => '&#23457;&#25209;',
		"modify_delete_header" => '&lt;b&gt;&#20462;&#25913; / &#21024;&#38500; &lt;/b&gt;',
		"new_emailSubject" => '&#26032;&#20449;&#24687;',
		"next_page" => '&#19979;&#19968;&#26465;',
		"no_entries" => '&#26080;&#20449;&#24687;&#12290;',
		"no_javascript_for_post" => '&#35831;&#24320;&#21551;Javascript &#25903;&#25345;&#12290;',
		"no_links_allowed" => '&#19981;&#20801;&#35768;&#27492;&#31867;&#38142;&#25509;&#12290;',
		"page_name" => '&#39029;&#65283;',
		"pagenum_divider" => '...',
		"pi1_plus_wiz_description" => '&#28155;&#21152;&#65288;&#31095;&#21578;&#65289;&#36830;&#25509;&#20449;&#24687;',
		"pi1_title" => 'WEC&#65288;&#31095;&#21578;&#65289;&#36830;&#25509;&#25554;&#20214;',
		"post_bad_words" => '&#20320;&#30340;&#20449;&#24687;&#21253;&#21547;&#26080;&#20801;&#35768;&#30340;&#25991;&#23383;&#25152;&#20197;&#24050;&#32463;&#34987;&#21024;&#38500;&#12290;',
		"post_duplicate" => '&#24744;&#30340;&#20449;&#24687;&#24050;&#32463;&#34987;&#28155;&#21152;&#12290;',
		"prev_page" => '&#21069;&#19968;&#65288;&#39029;&#65289;',
		"respond_btn" => '&#22238;&#22797;',
		"respond_error1" => '&#22240;&#20026;&#30005;&#37038;&#22320;&#22336;&#19981;&#27491;&#30830;&#65292;&#24744;&#30340;&#22238;&#22797;&#26080;&#27861;&#25104;&#21151;&#21457;&#36865;&#12290;',
		"respond_error2" => '&#22238;&#22797;&#26080;&#27861;&#21457;&#36865;&#12290;',
		"respond_header" => '&#27492;&#37038;&#20214;&#22238;&#22797;&#24744;&#20197;&#19979;&#35831;&#27714;&#65306;',
		"respond_success" => '&#22238;&#22797;&#24050;&#21457;&#36865; &#12290;',
		"responseform_cancel" => '&#21462;&#28040;',
		"responseform_email" => '&#30005;&#37038;&#22320;&#22336;',
		"responseform_message" => '&#24744;&#30340;&#22238;&#22797;',
		"responseform_name" => '&#24744;&#30340;&#22995;&#21517;',
		"responseform_subject" => '&#20027;&#39064;',
		"responseform_submit" => '&#22238;&#22797;',
		"show_required_text" => '&lt;span class=&quot;tx-wecconnector-form-requiredMarker&quot;&gt;*&lt;/span&gt; =&#24517;&#22635;&#39033;',
		"submit_button_label" => '&#25552;&#20132;',
		"subscribe_btn" => '&#35746;&#38405;',
		"subscribe_error1" => '&#35831;&#25552;&#20379;&#24744;&#30340;&#30005;&#37038;&#22320;&#22336;&#12290;',
		"subscribe_error2" => '&#35831;&#25552;&#20379;&#24744;&#27491;&#30830;&#30340;&#30005;&#37038;&#22320;&#22336;&#12290;(&#20363;. mothergoose@aol.com, jacksprat@yahoo.com)',
		"subscribe_error3" => '&#20320;&#30340;&#30005;&#37038;&#22320;&#22336;&#24050;&#32463;&#22312;&#22320;&#22336;&#21015;&#34920;&#12290;',
		"subscribe_success" => '&#35746;&#38405;&#25104;&#21151;&#12290;',
		"subscribeform_cancel" => '&#21462;&#28040;',
		"subscribeform_email" => '&#30005;&#37038;',
		"subscribeform_name" => '&#22995;&#21517;',
		"subscribeform_submit_sub" => '&#35746;&#38405;',
		"subscribeform_submit_unsub" => '&#21462;&#28040;&#35746;&#38405;',
		"textcaptcha_bad" => '&#35831;&#22635;&#20889;„&#30495;&#20154;&#30830;&#35748;&#65311;‰&#39033;',
		"textcaptcha_field" => '&#30495;&#20154;&#30830;&#35748;&#65311;',
		"too_many_links" => '&#22826;&#22810;&#38142;&#25509;-- &#20801;&#35768;&#30340;&#38142;&#25509;&#25968;',
		"unsubscribe_btn" => '&#21462;&#28040;&#35746;&#38405;',
		"unsubscribe_error" => '&#24744;&#27809;&#26377;&#35746;&#38405;-- &#35831;&#30830;&#23450;&#30005;&#37038;&#25340;&#20889;&#27491;&#30830;&#12290;',
		"viewall_btn" => '&#26174;&#31034;&#25152;&#26377;',

		"postedby_text" => '&#21457;&#24067;&#32773;&#65306;',
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => array (
		'admin_btn' => 'Admin',
		'admin_exit' => 'Exit',
		'admin_menu_header' => 'Admin Menu',
		'admin_show_subscribers' => 'Show Subscribers',
		'anonymous' => 'Anonym',
		'back' => 'Vissza',
		'back_button' => 'Vissza',
		'cancel_btn' => 'MÈgse',
		'captcha_bad' => 'KÈrlek Ì≠rd be a szˆveget a kÈp ellenırzÈshez ˙jra.',
		'choose_category' => 'V·laszz egy kategÛri·t:',
		'delete_btn' => 'Tˆrˆl',
		'delete_cannot' => 'Nincs jogod ennek a bejegyzÈsnek a tˆrlÈsÈhez.',
		'delete_confirm' => 'Biztos vagy benne, hogy ezt a bejegyzÈst tˆrˆlni akarod?',
		'delete_failure' => 'ProblÈma adÛdott a bejegyzÈs tˆrlÈsÈnÈl.',
		'delete_success' => 'Te tˆrˆlted a bejegyzÈst.',
		'display_header' => 'Current',
		'display_header_plurals' => 's',
		'display_total' => 'ˆsszesen',
		'display_total_category' => 'in category',
		'edit_btn' => 'Szerkeszt',
		'edit_denied' => 'Neked nincs jogod ezt az ¸zenetet megv·ltoztatni.',
		'edit_failure' => 'Te nem tudtad megv·ltoztatni ezt az ¸zenetet.',
		'email_category' => 'KategÛria: ',
		'email_from' => 'tÛl:',
		'email_gotolink' => 'Link megl·togat·sa:',
		'email_locatedin' => 'Bevitel: ',
		'email_message' => '‹zenet:',
		'email_moderateMsg' => 'Moder·ljad ezt az ¸zenetet ',
		'email_moderateMsgHeader' => 'Egy ˙j ¸zenetet moder·lni kell:',
		'email_none' => '<noreply@here.com>',
		'email_notify' => 'Fontos:',
		'email_postedby' => 'Õrta:',
		'email_subject' => 'T·rgy:',
		'email_unsubscribe' => '-------------------------------------------<br />Ha az elıfizetÈst be akarod fejezni, vagyis nem akarsz tˆbb emailt kapni, kattints erre a linkre: ',
		'entry_description' => 'LekÈrdezÈs',
		'form_address' => 'Utca',
		'form_business_name' => 'CÈg neve',
		'form_category' => 'KategÛria kiv·laszt·s',
		'form_city' => 'V·ros',
		'form_contact_name' => 'Kontakt szemÈly',
		'form_country' => 'Orsz·g',
		'form_email' => 'Email cÌ≠med',
		'form_email_instructions' => 'Figyelem: Az email-cÌ≠med ezen az oldalon nem lesz megmutatva.',
		'form_error' => 'A kˆvetkezı hib·k lÈptek fel:',
		'form_image' => 'KÈp kiv·laszt·s',
		'form_invalid_field' => '…rvÈnytelen adat',
		'form_invalid_field_length' => 'Ennek a mezınek a tartalma t˙l hossz˙',
		'form_location' => 'CÌ≠med',
		'form_location_instructions' => 'KÈrlek add meg a v·rosod',
		'form_message' => '‹zenet',
		'form_message_instructions' => 'KÈrlek adj meg egy leÌ≠r·st. Veled email-en kereszt¸l lesz felvÈve a kapcsolat.',
		'form_name' => 'Neved',
		'form_name_instructions' => 'KÈrlek add meg a neved',
		'form_phone' => 'Telefon',
		'form_required_blank' => 'Ezt a mezıt kˆtelezı kitˆlteni',
		'form_state' => 'Megye',
		'form_subject' => 'T·rgy',
		'form_subject_instructions' => 'KÈrlek adj meg egy t·rgyat (cÌ≠met)',
		'form_submit' => 'Elk¸ld',
		'form_toggleOff' => '‹zenet elrejtÈse',
		'form_toggleOn' => '‹zenet hozz·ad·sa',
		'form_website_url' => 'Weboldal cÌ≠me',
		'form_zipcode' => 'Postai ir·nyÌ≠tÛsz·m',
		'login_to_post' => 'Be kell jelentkezzÈl, hogy itt k¸ldeni tudj·l.',
		'login_to_reply' => 'Ha erre v·laszolni akarsz, akkor be kell jelentkezzÈl.',
		'message_added' => 'A bejegyzÈsed hozz· lett adva a list·hoz.',
		'message_moderated' => 'Ez a rÈsz moder·lt -- Akkor l·tszik a bejegyzÈsed, ha el lett fogadva.',
		'message_updated' => 'A bejegyzÈsed meg lett v·ltoztatva.',
		'moderate_btn' => 'Moder·l·s',
		'modify_delete_header' => '<h3>Szerkeszt / Tˆrˆl</h3>',
		'modify_request' => '‹zenet v·ltoztat·sa',
		'new_emailSubject' => '⁄j',
		'next_page' => 'Kˆvetkezı',
		'no_entries' => 'Jelenleg nincs ¸zenet.',
		'no_links_allowed' => 'Itt nem k¸ldhetsz linkeket.',
		'no_subject' => '(nincs t·rgy)',
		'page_name' => 'Oldal #',
		'pagenum_divider' => '...',
		'pi1_plus_wiz_description' => '(Gebets-) Connector hinzuf¸gen',
		'pi1_title' => 'WEC Connector',
		'post_bad_words' => 'A bejegyzÈsed nem kÌ≠v·natos szavakat tartalmaz. Vissza lett utasÌtva.',
		'post_duplicate' => 'A bejegyzÈsed m·r hozz· lett adva a list·hoz. Nem sz¸ksÈges mÈg egyszer elk¸ldeni.',
		'prev_page' => 'Elızı',
		'respond_btn' => 'V·lasz',
		'respond_error1' => 'A v·laszod nem lett elk¸ldve. Hib·s e-mail cÌ≠met adt·l meg.',
		'respond_error2' => 'A v·laszod nem lett elk¸ldve.',
		'respond_header' => 'Ez az e-mail egy kÈrÈsre lett elk¸ldve innen: ',
		'respond_success' => 'A bejegyzÈsed sikeresen el lett k¸ldve.',
		'responseform_cancel' => 'MÈgse',
		'responseform_email' => 'Email-cÌ≠m',
		'responseform_message' => 'V·lasz ¸zenet',
		'responseform_name' => 'Neved',
		'responseform_subject' => 'T·rgy',
		'responseform_submit' => 'V·lasz k¸ldÈs',
		'show_required_text' => '* = sz¸ksÈges mezık',
		'submit_button_label' => 'Elk¸ld',
		'subscribe_btn' => 'Megfigyel',
		'subscribe_error1' => 'Add meg az e-mail cÌ≠medet.',
		'subscribe_error2' => 'Add meg az e-mail cÌ≠medet a kˆvetkezı form·ban nev@web.hu an (pl. kacsamama@aol.com, jacksprat@yahoo.com)',
		'subscribe_error3' => 'Te megfigyeled m·r ezt a list·t.',
		'subscribe_success' => 'Te megfigyeled ezt a list·t.',
		'subscribeform_cancel' => 'MÈgse',
		'subscribeform_email' => 'Email-cÌ≠m',
		'subscribeform_name' => 'Neved',
		'subscribeform_submit_sub' => 'Megfigyel',
		'subscribeform_submit_unsub' => 'MegfigyelÈst befejez',
		'textcaptcha_bad' => 'Ki kell tˆltsed ezt a mezıt: "Te egy szemÈly vagy?"',
		'textcaptcha_field' => 'Te egy szemÈly vagy?',
		'too_many_links' => 'T˙l sok linket tal·lt -- csak engedÈlyezett ',
		'unsubscribe_error' => 'Te nem tudod ezt a list·t elıfizetni -- Az email-cÌ≠med nem lett elfogadva. Ellenırizd ismÈt az email-cÌ≠medet Ès prÛb·ld meg ˙jra.',
		'viewall_btn' => 'Mindent mutat',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>