<?php
/**
 * Language labels for module "tools_txccawstatsM1"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'title' => 'AWStats logfile analysis',
		'aws_helpText' => 'The logfiles have to be named *.log or *log*.txt<br>examples: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>ERROR:</strong><br>The logfile directory \'\' configured in typo3conf/localconf.php as \'\' was NOT found!',
		'aws_errLogfileDir_conf' => '<strong>ERROR:</strong><br>The logfile directory is not configured in typo3conf/localconf.php like this:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>ERROR:</strong><br>Could not create directory \'\' to store data for AWStats. Please check write permissions.',
		'aws_noLogfilesFound' => '<strong>ERROR:</strong><br>No logfiles found in directory \'\'<br>The logfiles have to be named *.log or *log*.txt<br>examples: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'save configuration',
		'aws_btnEditConf' => 'edit configuration',
		'aws_hdrSelectLogfile' => 'Select logfile to view analysis:',
		'aws_hdrConfLogfile' => 'Configure logfiles:',
		'aws_msg1ConfLogfile' => 'You have to configure following logfiles:',
		'aws_msg2ConfLogfile' => 'Please enter the domain(s) for wich the logfile is. For multiple domains seperate them with komma. The main domain first.<br>example: <strong>www.mydomain.com,mydomain.com,sub.mydomain.com</strong><br>You can hide files with <strong>-</strong> (minus)<br>',
		'aws_hdrEditLogfile' => 'Edit logfile configuration:',
		'aws_btnClearCache' => 'Clear cache',
		'aws_hdrClearCache' => 'Clear AWStat cache',
		'aws_descrClearCache' => 'Clearing the cache may be needed with upgrade to new AWStats versions.',
		'aws_cacheCleared' => 'Cleared caches.',
	),
	'dk' => Array (
	),
	'de' => Array (
		'title' => 'AWStats Logfile Analyse',
		'aws_helpText' => 'Die Logfiles müssen auf folgendes Muster passen: *.log oder *log*.txt<br>Beispiele: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>FEHLER:</strong><br>The logfile directory \'\' configured in typo3conf/localconf.php as \'\' was NOT found!',
		'aws_errLogfileDir_conf' => '<strong>FEHLER:</strong><br>The logfile directory is not configured in typo3conf/localconf.php like this:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>FEHLER:</strong><br>Could not create directory \'\' to store data for AWStats. Please check write permissions.',
		'aws_noLogfilesFound' => '<strong>FEHLER:</strong><br>No logfiles found in directory \'\'<br>The logfiles have to be named *.log or *log*.txt<br>examples: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'Konfiguration sichern',
		'aws_btnEditConf' => 'Konfiguration bearbeiten',
		'aws_hdrSelectLogfile' => 'Wählen Sie ein Logfile für die Analyse aus:',
		'aws_hdrConfLogfile' => 'Logfiles konfigurieren:',
		'aws_msg1ConfLogfile' => 'Sie müssen folgende Logfiles konfigurieren:',
		'aws_msg2ConfLogfile' => 'Bitte die Domain(s) für das Logfile eintragen. Mehrere Domains mit Komma trennen. Die Haupt-Domain als erstes.<br>Beispiel: <strong>www.mydomain.com,mydomain.com,sub.mydomain.com</strong><br>Ist eine Datei kein Logfile, dann <strong>-</strong> (minus) eintragen.<br>',
		'aws_hdrEditLogfile' => 'Logfile Konfiguration bearbeiten:',
		'aws_btnClearCache' => 'Cache löschen',
		'aws_hdrClearCache' => 'AWStat Cache löschen',
		'aws_descrClearCache' => 'Das löschen des Cache ist unter Umständen beim Upgrade auf eine neue AWStats Version notwendig.',
		'aws_cacheCleared' => 'Caches gelöscht.',
	),
	'no' => Array (
		'title' => 'AWStats lofil analyse',
		'aws_helpText' => 'Loggfilen må ha filnavn med *.log eller *log*.txt<br>f.eks.: <strong>mitt-domene.log   logfile.txt   website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>ERROR:</strong><br>Loggfil folderen " konfigurert i typo3conf/localconf.php som " ble ikke funnet',
		'aws_errLogfileDir_conf' => '<strong>ERROR:</strong>br>Logfil folderen er ikke konfigurert i typo3conf/localconf.php som følger:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>ERROR:</strong><br>Kunne ikke lage folder " til å lagre data for AWStats. Vær vennlig å sjekk skrive rettigheter.',
		'aws_noLogfilesFound' => '<strong>ERROR:</strong><br>Ingen logfiler er funnet i folderen "<br>Loggfilen må ha filnavn med *.log eller *log*.txt<br>f.eks.: <strong>mitt-domene.log   logfile.txt   website-log.txt</strong>',
		'aws_btnSaveConf' => 'lagre konfigurasjon',
		'aws_btnEditConf' => 'rediger konfigurasjon',
		'aws_hdrSelectLogfile' => 'Velg logfil for å se analyse',
		'aws_hdrConfLogfile' => 'Konfigurer logfil',
		'aws_msg1ConfLogfile' => 'Du må konfigurere følgende logfiler',
		'aws_msg2ConfLogfile' => 'Tast inn domene(t) for loggfilen. Flere domener separeres med komma. Hoveddomenet først. <br> Eksempel : <strong>www.mittdomene.no,mittdomene.no,sub.mittdomene.no</strong><br>Du kan skjule filer med <strong>-</strong> (minus)<br>',
		'aws_hdrEditLogfile' => 'Rediger loggfil konfigurasjon',
		'aws_btnClearCache' => 'Tøm buffer',
		'aws_hdrClearCache' => 'Tøm AWStat buffer',
		'aws_descrClearCache' => 'Å tømme bufferet er muligens nødvendig ved oppgradering til nyere AWStats versjon',
		'aws_cacheCleared' => 'Bufferet er tømt',
	),
	'it' => Array (
	),
	'fr' => Array (
		'title' => 'AWStats analyse statistique',
		'aws_helpText' => 'Les fichiers journaux doivent être nommés *.log ou *log*.txt<br>ex: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>ERREUR:</strong><br>Le dossier des fichiers journaux " configuré dans typo3conf/localconf.php comme " n\'a pas été trouvé!',
		'aws_errLogfileDir_conf' => '<strong>ERREUR:</strong><br>Le dossier des fichiers journaux n\'est pas configuré dans typo3conf/localconf.php comme cela:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '] <strong>ERREUR:</strong><br>Impossible de créer le dossier \'\' pour stocker les données de AWStats. Veuillez contrôler les droits d\'accès.',
		'aws_noLogfilesFound' => '<strong>ERREUR:</strong><br>Aucun fichier journal trouvé dans le dossier \'\'<br>Les fichiers journaux doivent être nommés *.log ou *log*.txt<br>ex: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'Sauver la configuration',
		'aws_btnEditConf' => 'Editer la configuration',
		'aws_hdrSelectLogfile' => 'Séléctionnez le journal à analyser:',
		'aws_hdrConfLogfile' => 'Configurer les fichiers journaux:',
		'aws_msg1ConfLogfile' => 'Vous devez configurez les fichiers journaux suivant:',
		'aws_msg2ConfLogfile' => 'Veuillez préciser le domaine au quel se raporte le fichier journal . Pour les domaines multiples, séparez les par des virgules. Le domaine principale en premier.<br>ex.: <strong>www.mydomain.com,mydomain.com,sub.mydomain.com</strong><br>Vous pouvez cacher des fichiers avec <strong>-</strong> (moins)<br>',
		'aws_hdrEditLogfile' => 'Editer la configuration des fichiers journaux:',
		'aws_btnClearCache' => 'Effacer le cache',
		'aws_hdrClearCache' => 'Effacer le cache AWStats',
		'aws_descrClearCache' => 'Effacer le cache peut-être obligatoire lors de la mise à jour vers une nouvelle version de AWStats.',
		'aws_cacheCleared' => 'Caches effacés.',
	),
	'es' => Array (
	),
	'nl' => Array (
		'title' => 'AWStats logbestand analyse',
		'aws_helpText' => 'De logbestanden moeten *.log of *log*.txt genoemd worden<br>voorbeelden:<strong>mijn-domein.log.logbestand.txt  website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>FOUT:</strong><br>De logbestand map \'\' ingesteld in typo3conf/localconf.php als \'\' kon NIET worden gevonden!',
		'aws_errLogfileDir_conf' => '<strong>FOUT:</strong><br>De logbestand map is in typo3conf/localconf.php niet geconfigureerd op de volgende manier: <br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;"',
		'aws_errCreateLogfileDir' => '<strong>FOUT:</strong><br>Kon directory \'\' voor de opslag van AWStats data niet aanmaken. Kijk a.u.b. uw schrijf-permissies na.',
		'aws_noLogfilesFound' => '<strong>FOUT:</strong><br>Geen logbestanden gevonden in de map \'\' <br>De logbestanden moeten *.log of *.log*.txt genoemd worden.<br>voorbeelden:<strong>mijn-domein.log  logbestand.txt  website-log.tct</strong>',
		'aws_btnSaveConf' => 'opslaan configuratie',
		'aws_btnEditConf' => 'bewerken configuratie',
		'aws_hdrSelectLogfile' => 'Selecteer logbestand en bekijk de analyse:',
		'aws_hdrConfLogfile' => 'Configureer logbestanden:',
		'aws_msg1ConfLogfile' => 'U moet de volgende logbestanden configureren:',
		'aws_msg2ConfLogfile' => 'Vul a.u.b. de domein(en) in waarvoor het logbestand is. Scheidt meerdere domeinen met een komma. Het hoofddomein komt eerst.<br>voorbeeld:<strong>www.mijndomein,com,mijndomein.com,sub.mijndomein.com</strong><br>U kunt bestanden verbergen met <strong>-</strong>(minus)<br>',
		'aws_hdrEditLogfile' => 'Logbestand configuratie aanpassen:',
		'aws_btnClearCache' => 'Cache legen',
		'aws_hdrClearCache' => 'AWStats cache legen',
		'aws_descrClearCache' => 'Bij het upgraden naar een nieuwe AWStats versie kan het nodig zijn de cache te lagen',
		'aws_cacheCleared' => 'Cache geleegd.',
	),
	'cz' => Array (
		'title' => 'AWStats analıza logù',
		'aws_helpText' => 'Soubory s logy',
		'aws_errLogfileDir' => '<strong>CHYBA:</strong><br>Adresáø s logy \'\', specifikovanı v typo3conf/localconf.php jako \'\' NEBYL nalezen!',
		'aws_errLogfileDir_conf' => '<strong>CHYBA:</strong><br>Adresáø s logy není specifikovanı v typo3conf/localconf.php jako napø:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/pro_priklad/;',
		'aws_errCreateLogfileDir' => '<strong>CHYBA:</strong><br>Nelze vytvoøit adresáø \'\' k uloení dat pro AWStats. Zkontrolujte prosím pøístupová práva.',
		'aws_noLogfilesFound' => '<strong>CHYBA:</strong><br>V adresáøi \'\' nebyly nalezeny ádné log soubory.<br>Log soubory by mìly bıt pojmenovanı jako *.log nebo *log*.txt<br>Pøíklady: <strong>moje-domena.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'uloit konfiguraci',
		'aws_btnEditConf' => 'upravit konfiguraci',
		'aws_hdrSelectLogfile' => 'Vyberte log soubor pro zobrazení analızy:',
		'aws_hdrConfLogfile' => 'Konfigurovat log soubory',
		'aws_msg1ConfLogfile' => 'Je tøeba konfigurovat následující log soubory:',
		'aws_msg2ConfLogfile' => 'Prosím vlote domény, kterım pøísluší tento log soubor. Pro více domén tyto oddìlte pomocí èárky. Hlavní doménu vlote jako první.<br>Pøíklad:<strong>www.mojedomena.cz,mojedomena.cz,poddomena.mojedomena.cz</strong><br>Skrıt soubory mùete pomocí <strong>-</strong> (mínus).<br>',
		'aws_hdrEditLogfile' => 'Upravit konfiguraci log souborù',
		'aws_btnClearCache' => 'Vyprázdnit cache',
		'aws_hdrClearCache' => 'Vyprázdnit keš AWStats',
		'aws_descrClearCache' => 'Se zmìnou verze AWStats je tøeba vyprázdit cache.',
		'aws_cacheCleared' => 'Cache vyprázdnìna.',
	),
	'pl' => Array (
		'title' => 'AWStats analiza logów',
		'aws_helpText' => 'Nazwy plików logów musz± byæ postaci *.log albo *log*.txt<br>przyk³ad: <strong>moja-domena.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>B£¡D:</strong><br>Katalog z plikami logów \'\' skonfigurowany w typo3conf/localconf.php jako \'\' nie zosta³ znaleziony!',
		'aws_errLogfileDir_conf' => '<strong>B£¡D:</strong><br>Katalog z plikami logów nie jest skonfigurowany w typo3conf/localconf.php np. w ten sposób:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/logi/;',
		'aws_errCreateLogfileDir' => '<strong>B£¡D:</strong><br>Nie mogê utworzyæ katalogu \'\' przechowuj±cego dane AWStats. Sprawd¼ prawa zapisu.',
		'aws_noLogfilesFound' => '<strong>B£¡D:</strong><br>Nie znaleziono plików logów w katalogu \'\'<br>Nazwy plików logów musz± byæ postaci *.log albo *log*.txt<br>przyk³ad: <strong>moja-domena.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'Zapisz konfiguracjê',
		'aws_btnEditConf' => 'Edytuj konfiguracjê',
		'aws_hdrSelectLogfile' => 'Wybierz plik logów do analizy:',
		'aws_hdrConfLogfile' => 'Konfiguruj pliki logów:',
		'aws_msg1ConfLogfile' => 'Skonfigurowa³e¶ poni¿sze pliki logów:',
		'aws_msg2ConfLogfile' => 'Wprowad¼ nazwy domen dla których generowany jest log. Domeny oddzielaj przecinkami. G³ówna domena najpierw.<br>Przyk³ad: <strong>www.mojadomena.pl,mojadomena.com.pl</strong><br>Mo¿esz ukryæ pliki u¿ywaj±c <strong>-</strong> (minus)<br>',
		'aws_hdrEditLogfile' => 'Edytuj konfiguracjê pliku logów:',
		'aws_btnClearCache' => 'Wyczy¶æ cache',
		'aws_hdrClearCache' => 'Wyczy¶æ cache AWStat',
		'aws_descrClearCache' => 'Przy zmianie wersji AWStats moze byæ wymagane wyczyszczenie cache\'u.',
		'aws_cacheCleared' => 'Wyczyszczono cache.',
	),
	'si' => Array (
		'title' => 'AWStats analiza obiska',
		'aws_helpText' => 'Dnevniki morajo biti poimenovani *.log ali *log*.txt<br>primeri: <strong>moja-domena.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>NAPAKA:</strong><br>Pot do dnevnikov \'\' nastavljena v typo3conf/localconf.php kot \'\' NE obstaja!',
		'aws_errLogfileDir_conf' => '<strong>NAPAKA:</strong><br>Pot do dnevnikov v typo3conf/localconf.php ni pravilno nastavljena. Primer:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>NAPAKA:</strong><br>Mape \'\' za shranjevanje podatkov za AWStats ni bilo mogoèe ustvariti. Preverite privilegije za pisanje.',
		'aws_noLogfilesFound' => '<strong>NAPAKA:</strong><br>V mapi \'\' ni datotek.<br>Dnevniki morajo biti poimenovani *.log ali *log*.txt<br>primeri: <strong>moja-domena.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'shrani nastavitve',
		'aws_btnEditConf' => 'uredi nastavitve',
		'aws_hdrSelectLogfile' => 'Izberi dnevnik za analizo:',
		'aws_hdrConfLogfile' => 'Nastavi dnevnike:',
		'aws_msg1ConfLogfile' => 'Nastaviti morate naslednje dnevnike:',
		'aws_msg2ConfLogfile' => 'Vpišite domene, za katere je ta dnevnik. Pri veèih domenah jih loèite z vejico. Glavna domena najprej. <br>primer: <strong>www.mydomain.com,mydomain.com,sub.mydomain.com</strong><br>Datoteke lahko skrijete z znakom<strong>-</strong> (minus)<br>',
		'aws_hdrEditLogfile' => 'Uredi nastavitve dnevnika:',
		'aws_btnClearCache' => 'Izprazni predpomnilnik:',
		'aws_hdrClearCache' => 'Izprazni AWStats predpomnilnik:',
		'aws_descrClearCache' => 'Pri nadgradnji programa AWStats je vèasih potrebno brisanje predpomnilnika.',
		'aws_cacheCleared' => 'Prepomnilniki izpraznjeni.',
	),
	'fi' => Array (
		'title' => 'AWStats lokitiedosto analyysi',
		'aws_helpText' => 'Lokitiedostot on nimettävä *.log or *log*.txt<br>Esimerkit: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>ERROR:</strong><br>Lokitiedosto hakemisto \'\' configured in typo3conf/localconf.php as \'\' ei löytynyt!',
		'aws_errLogfileDir_conf' => '<strong>ERROR:</strong><br>Lokitiedostohakemistoa ei ole konfiguroitu typo3conf/localconf.php kuten esimerkiksi:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>ERROR:</strong><br>Hakemistoa ei voitu luoda \'\' tallentamaan AWStats tietoja. Tarkista kirjoitus oikeudet.',
		'aws_noLogfilesFound' => '<strong>ERROR:</strong><br>Hakemistosta ei löytynyt lokitiedostoja \'\'<br>Lokitiedostot on nimettävä *.log or *log*.txt<br>Esimerkiksi: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'tallenna konfiguraatio',
		'aws_btnEditConf' => 'muotoile konfiguraatiota',
		'aws_hdrSelectLogfile' => 'Valitse lokitiedosto jonka analyysin haluat nähdä:',
		'aws_hdrConfLogfile' => 'Konfiguroi lokitiedostoja',
		'aws_msg1ConfLogfile' => 'Olet konfiguroinut seuraavia lokitiedostoja:',
		'aws_msg2ConfLogfile' => 'Anna domain jolle lokitiedosto on. Jos on useampia domaineja erottele ne pilkuin. Päädomaini ensiksi.<br>esimerkki:',
		'aws_hdrEditLogfile' => 'Muotoile lokitiedoston konfiguraatiota',
		'aws_btnClearCache' => 'Tyhejennä välimuisti',
		'aws_hdrClearCache' => 'Tyhjennä AWStatin välimuisti',
		'aws_descrClearCache' => 'Välimuistien tyhjennys voi olla tarpeellinen päivitettäessä AWStatsin uuteen versioon.',
		'aws_cacheCleared' => 'Tyhjennetty välimuistit',
	),
	'tr' => Array (
		'title' => 'AWStat logdosyası analizi',
		'aws_btnSaveConf' => 'konfigürasyonu kaydet',
		'aws_btnEditConf' => 'konfigürasyonu düzelt',
		'aws_hdrSelectLogfile' => 'Logdosyasının analiz gösterimini seç',
		'aws_hdrConfLogfile' => 'Logdosyaları konfigürasyonu:',
		'aws_msg1ConfLogfile' => 'Aşağıdaki logdosyalarını konfigüre etmelisiniz:',
		'aws_hdrEditLogfile' => 'Logdosyaları konfigürasyonunu düzelt:',
		'aws_btnClearCache' => 'Önbelleği temizle',
		'aws_hdrClearCache' => 'AWStat belleğini temizle',
		'aws_descrClearCache' => 'Önbellek temizleniyor daha yüksek AWStat sürümünü yüklemeniz gerekli olabilir.',
		'aws_cacheCleared' => 'Önbellek temizlendi.',
	),
	'se' => Array (
		'title' => 'Analysering av AWStats log-filen',
		'aws_helpText' => 'Logfilen bör ha namnet *.log eller *log*.txt<br>exempel: <strong>my-domain.log logfile.text website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>ETT FEL HAR UPPSTÅTT:</strong><br>Logfilens katalog \'\' som konfigurerats i typo3conf/localconf.php med namnet \'\' hittades INTE!',
		'aws_errLogfileDir_conf' => '<strong>ETT FEL HAR UPPSTÅTT:</strong><br>Logfilens katalog har inte konfigurerats i typo3conf/localconf.php enligt detta exempel:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>ETT FEL HAR UPPSTÅTT:</strong><br>Det går inte att skapa katalogen \'\' för att lagra data för AWStats. Vänligen kontrollera skrivrättigheterna.',
		'aws_noLogfilesFound' => '<strong>ETT FEL HAR UPPSTÅTT:</strong>Ingen logfil hittades i katalogen \'\'<br>Logfilen bör ha ett namn som *.log eller *log*.txt<br>Exempel: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'spara konfigurationen',
		'aws_btnEditConf' => 'ändra konfigurationen',
		'aws_hdrSelectLogfile' => 'Välj vilken logfil som skall analyseras:',
		'aws_hdrConfLogfile' => 'Konfigurera logfilen:',
		'aws_msg1ConfLogfile' => 'Du bör konfigurera följande logfiler:',
		'aws_msg2ConfLogfile' => 'Vänligen ge det domain till vilket logfilen hör. Har du flere domain bör dom separeras med ett kommatecken. Ange huvud-domainet först.<br>Exempel: <strong>www.mydomain.com,mydomain.com,sub.mydomain.com</strong><br>. Filer kan gömmas med ett minusstreck <strong>-</strong><br>',
		'aws_hdrEditLogfile' => 'Ändra logfilens konfiguration:',
		'aws_btnClearCache' => 'Töm cache-minnet',
		'aws_hdrClearCache' => 'Töm AWStats cache-minne',
		'aws_descrClearCache' => 'Det kan vara nödvändigt att tömma cache-minnet då du uppgraderar till en ny version av AWStats.',
		'aws_cacheCleared' => 'Cache-minnet tömt.',
	),
	'pt' => Array (
		'title' => 'AWStats análise de diários',
		'aws_helpText' => 'Os diários tem de ser nomeados *.log ou *log*.txt<br>exemplos: <strong>my-domain.log</strong> ou <strong>logfile.txt</strong> ou <strong>website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>ERRO:<strong><br>A directoria de diários \'\' configurada em typo3conf/localconf.php como \'\' NÃO existe!',
		'aws_errLogfileDir_conf' => '<strong>ERRO:<strong><br>A directoria de diários não está configurada em typo3conf/localconf.php como por exemplo:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/por_exemplo/;',
		'aws_errCreateLogfileDir' => '<strong>ERRO:</strong><br>Não é possível criar a directoria \'\' para guardar os dados de AWStats. Verifique as permissões de escrita.',
		'aws_noLogfilesFound' => '<strong>ERROR:</strong><br>Nenhum diários encontrado na directoria \'\'<br>Os diários tem de ser nomeados *.log ou *log*.txt<br>exemplos: <strong>my-domain.log</strong> ou <strong>logfile.txt</strong> ou <strong>website-log.txt</strong>',
		'aws_btnSaveConf' => 'salvar configuração',
		'aws_btnEditConf' => 'editar configuração',
		'aws_hdrSelectLogfile' => 'Selecionar diário a analisar:',
		'aws_hdrConfLogfile' => 'Configurar diários:',
		'aws_msg1ConfLogfile' => 'Tem de configurar os seguintes diários:',
		'aws_msg2ConfLogfile' => 'Introduza o(s) domínio(s) a que este diário pertence. Para multiplos domínios separe-os por vírgula. O domínio principal primeiro.<br>exemplo: <strong>www.meudominio.com,meudominio.com,sub.meudominio.com</strong><br>Pode ocultar ficheiros usando o sinal <strong>-</strong> (menos)<br>',
		'aws_hdrEditLogfile' => 'Editar configuração do diário:',
		'aws_btnClearCache' => 'Limpar cache',
		'aws_hdrClearCache' => 'Limpar cache do AWStats',
		'aws_descrClearCache' => 'Limpar a cache pode ser necessário ao actualizar para novas versões do AWStats.',
		'aws_cacheCleared' => 'Cache limpa.',
	),
	'ru' => Array (
		'title' => 'Àíàëèçàòîğ ëîã-ôàéëîâ AWStats',
		'aws_helpText' => 'Ëîã-ôàéëû äîëæíû íàçûâàòüñÿ *.log èëè *.log.txt<br />Ïğèìåğû: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>ÎØÈÁÊÀ:</strong><br />Êàòàëîã ñ ëîã-ôàéëàìè \'\', ñêîíôèãóğèğîâàíûé â typo3conf/localconf.php êàê \'\', íå áûë íàéäåí!',
		'aws_errLogfileDir_conf' => '<strong>ÎØÈÁÊÀ:</strong><br />Êàòàëîã ñ ëîã-ôàéëàìè íå ñêîíôèãóğèğîâàí â typo3conf/localconf.php êàê:<br />$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>ÎØÈÁÊÀ:</strong><br />Íå ìîãó ñîçäàòü êàòàëîã \'\', ãäå áóäóò õğàíèòüñÿ ôàéëû äëÿ AWStats. Ïîæàëóéñòà, ïğîâåğüòå ïğàâà íà çàïèñü.',
		'aws_noLogfilesFound' => '<strong>ÎØÈÁÊÀ:</strong><br />Ëîã-ôàéëû íå íàéäåíû â êàòàëîãå \'\'<br />Ëîã-ôàéëû äîëæíû íàçûâàòüñÿ *.log èëè *.log.txt<br />Ïğèìåğû: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'ñîõğàíèòü êîíôèãóğàöèş',
		'aws_btnEditConf' => 'èçìåíèòü êîíôèãóğàöèş',
		'aws_hdrSelectLogfile' => 'Âûáåğèòå ëîã-ôàéë äëÿ àíàëèçà:',
		'aws_hdrConfLogfile' => 'Ñêîíôèãóğèğîâàòü ëîã-ôàéëû:',
		'aws_msg1ConfLogfile' => 'Âàì íàäî ñêîíôèãóğèğîâàòü ñëåäóşùèå ëîã-ôàéëû:',
		'aws_msg2ConfLogfile' => 'Ïîæàëóéñòà, ââåäèòå äîìåíû, äëÿ êîòîğûõ áûë çàïèñàí ıòîò ëîã-ôàéë. Åñëè äîìåíîâ ìíîãî, ğàçäåëÿéòå èõ çàïÿòûìè. Ãëàâíûé äîìåí äîëæåí èäòè ïåğâûì.<br />Ïğèìåğ: <strong>www.mydomain.com,mydomain.com,sub.mydomain.com</strong><br />Âû ìîæåòå ñàğÿòàòü ôàéëû ñ ïîìîùüş <strong>-</strong> (ìèíóñ)<br />',
		'aws_hdrEditLogfile' => 'Èçìåíèòü êîíôèãóğàöèş ëîã-ôàéëà:',
		'aws_btnClearCache' => 'Î÷èñòèòü êıø',
		'aws_hdrClearCache' => 'Î÷èñòèòü êıø AWStats',
		'aws_descrClearCache' => 'Î÷èñòêà êıøà ìîæåò ïîòğåáîâàòüñÿ ïğè ïåğåõîäå íà íîâóş âåğñèş AWStats.',
		'aws_cacheCleared' => 'Êıøè î÷èùåíû.',
	),
	'ro' => Array (
		'aws_cacheCleared' => 'Sterge informatii stocate',
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
		'title' => 'AWStats naplófájl elemzés',
		'aws_helpText' => 'A naplófájloknak *.log vagy *log*.txt -szerû nevet kell adni.<br>példák:<strong>mydomain.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>HIBA:</strong><br>A "typo3conf/localconf.php-ban ... -ként konfigurált" naplófájl könyvtár NEM található!',
		'aws_errLogfileDir_conf' => '<strong>HIBA:</strong><br>A naplófájl könyvtár nincs konfigurálva a typo3conf/localconf.php fájlban, mint például ez:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>HIBA:</strong><br>A \'\'  nevû könyvtár nem hozható létre adattárolásra az AWStats részére. Ellenõrizd az írási jogosultságot.',
		'aws_noLogfilesFound' => '<strong>Hiba:</strong><br>A \'\' könyvtárban nincs naplófájl<br>A naplófájloknak *.log vagy *log*.txt -szerû nevet kell adni.<br>példák: <strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_btnSaveConf' => 'beállítás mentése',
		'aws_btnEditConf' => 'beállítás szerkesztése',
		'aws_hdrSelectLogfile' => 'Válaszd ki a vizsgálandó naplófájlt:',
		'aws_hdrConfLogfile' => 'Naplófájlok beállítása:',
		'aws_msg1ConfLogfile' => 'A következõ naplófájlokat kell konfigurálni:',
		'aws_msg2ConfLogfile' => 'Add meg, hogy melyik tartományokra van naplófájl. Töbszörös tartományokat vesszõvel válaszd el. Elõször a fõtartományt add meg.<br>példa: <strong>www.mydomain.com,mydomain.com,sub.mydomain.com</strong><br>A fájlokat elrejtheted a  <strong>-</strong> (minusz) jellel<br>',
		'aws_hdrEditLogfile' => 'Naplófájl konfiguráció szerkesztése',
		'aws_btnClearCache' => 'Cache törlése',
		'aws_hdrClearCache' => 'AWStat cache törlése',
		'aws_descrClearCache' => 'A cache törlése szükségessé válhat új AWStat verzióra történõ átállásnál.',
		'aws_cacheCleared' => 'Cache törölve.',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
		'title' => 'AWStats¤é»x¤ÀªR',
		'aws_helpText' => '¤é»x»İ­n©R¦W¬°*.log ©Î *log*.txt<br>¨Ò¡G<strong>my-domain.log logfile.txt website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>¿ù»~¡G</strong><br>§ä¤£¨ì¦btypo3conf/localconf.php ¤¤³]©wªº¤é»xÀÉ¸ê®Æ§¨¡I',
		'aws_errLogfileDir_conf' => '<strong>¿ù»~¡G</strong><br>¦btypo3conf/localconf.php ¤¤³]©wªº¤é»xÀÉ¸ê®Æ§¨¤£¬O¥H¤U®æ¦¡¡G<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/for_example/;',
		'aws_errCreateLogfileDir' => '<strong>¿ù»~¡G</strong><br>¤£¯à¥ß¸ê®Æ§¨"Àx¦sAWStatsªº¸ê®Æ¡C½ĞÀË¬dÅª¼gÅv­­¡C',
		'aws_noLogfilesFound' => '<strong>¿ù»~¡G</strong><br>¦b¸ê®Æ§¨¤¤§ä¤£¨ì¤é»xÀÉ®×" <br>¤é»xÀÉ­n©R¦W¬°*.log ©Î *log*.txt<br>¨Ò¡G<strong>my-domain.log logfile.txt website-log.txt<strong>',
		'aws_btnSaveConf' => 'Àx¦s³]©w',
		'aws_btnEditConf' => '­×§ï³]©w',
		'aws_hdrSelectLogfile' => '¿ï¾Ü¤é»xÀÉÀËµø¤ÀªR¡G',
		'aws_hdrConfLogfile' => '³]©w¤é»xÀÉ¡G',
		'aws_msg1ConfLogfile' => '§A»İ­n³]©w¥H¤U¤é»xÀÉ¡G',
		'aws_msg2ConfLogfile' => '½Ğ¿ï¾Ü¤é»xÀÉ°O¿ıªººô°ì (domains) ¡C¦p¦h©ó¤@­Óºô°ì¡A¥i¥Î¡u, ¡v¤À¶}¡C¥Dºô°ì©ñ¦b³Ì¥ı¡C¨Ò¡G<strong>www.mydomain.com,mydomain.com,sub.mydomain.com</strong><br>§A¥i¥H¥Î<strong>-</strong>(¡u-¡v) ÁôÂÃÀÉ®×',
		'aws_hdrEditLogfile' => '­×§ï¤é»xÀÉ³]©w:',
		'aws_btnClearCache' => '²M°£§Ö¨ú°O¾Ğ:',
		'aws_hdrClearCache' => '²M°£AWStat§Ö¨ú°O¾Ğ',
		'aws_descrClearCache' => '¤É¯Å¦Ü³Ì·sª© AWStats ¤]³\\»İ­n²M°£§Ö¨ú°O¾Ğ',
		'aws_cacheCleared' => '¤w²M°£§Ö¨ú°O¾Ğ',
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'title' => 'AWStats análise de diários',
		'aws_helpText' => 'Os diários têm de ser nomeados *.log ou *log*.txt<br>exemplos: <strong>meu-dominio.log</strong> ou <strong>arquivo-diario.txt</strong> ou <strong>website-log.txt</strong>',
		'aws_errLogfileDir' => '<strong>ERRO:<strong><br>O diretório de diários \'\' configurado em typo3conf/localconf.php como \'\' NÃO existe!',
		'aws_errLogfileDir_conf' => '<strong>ERRO:<strong><br>O diretório de diários não está configurado em typo3conf/localconf.php como por exemplo:<br>$TYPO3_CONF_VARS["FE"]["logfile_dir"]="fileadmin/por_exemplo/;',
		'aws_errCreateLogfileDir' => '<strong>ERRO:</strong><br>Não é possível criar a directoria \'\' para guardar os dados de AWStats. Verifique as permissões de escrita.',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>