<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-26 17:18

$extensionPath = t3lib_extMgm::extPath('feeditadvanced');
return array(
	'tx_feeditadvanced_frontendedit' => $extensionPath . 'controller/class.tx_feeditadvanced_frontendedit.php',
	'tx_feeditadvanced_ajax' => $extensionPath . 'service/ajax.php',
	'tx_feeditadvanced_adminpanel' => $extensionPath . 'view/class.tx_feeditadvanced_adminpanel.php',
	'tx_feeditadvanced_editpanel' => $extensionPath . 'view/class.tx_feeditadvanced_editpanel.php',
	'tx_feeditadvanced_getmainfields_preprocess' => $extensionPath . 'view/class.tx_feeditadvanced_getMainFields_preProcess.php',
	'tx_feeditadvanced_menu' => $extensionPath . 'view/class.tx_feeditadvanced_menu.php',
	'tx_feeditadvanced_newcontentelements' => $extensionPath . 'view/class.tx_feeditadvanced_newcontentelements.php',
	'tx_feeditadvanced_tceforms' => $extensionPath . 'view/class.tx_feeditadvanced_tceforms.php',
);
?>